### ISSUE TITLE
6.1 Release.

### ISSUE THREAD

**Issue by markhibberd** [argonaut-io/argonaut#118]
I want to release 6.1 soon after scalaz 7.1 is released, but there is a lot of work to be done. 

Definite list:
 - [ ] Review type support for Encode/Decode Json. There are a few things missing Array (#60), Byte (#71).
 - [ ] Printer improvements (#117)
 - [x] Revisit access to history of HCursor.
 - [ ] Add utilities to help hand building codecs for sum types (#65, #105). Note there are some good combinators in scodec that are worth looking at, plus some I have posted to the mailing list/irc at various times.
 - [x] Review and Merge in shapeless generic support for auto derived codecs (#108, #109)

 - [ ] Add a combinator that checks for field names as well as number of fields for case codecs, see (#104).
 - [ ] Improvements to errors (#104).
 - [x] Java 8 issue (#95). 
 - [x] Unsafe mutual recursion in codecs must get removed (#83)
 - [ ] Clean-up and document auto-codecs (#129)

Maybe list (probably 6.2 now):
 - [ ] Fix jNumber (#68, #73, #98, #111, #116)
 - [ ] Better support for recursive types (#130)
 - [ ] Diff support (#99)
 - [ ] QuasiQuoter for json (#81).
 - [ ] Jawn support.
 - [ ] ByteBuffer, Array[Byte], ByteVector parsing support.
 - [ ] Scalaz-stream support (separate module)

**Comment by nafg** [comment]
Wasn't this released already?
Btw the site doesn't reflect that -- it seems a bit outdated

**Comment by seanparsons** [comment]
@nafg Yeah, it's on my list of many things.
